# Generated by Django 4.2.2 on 2023-06-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerMinute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(max_length=10)),
                ("player_name", models.CharField(max_length=50)),
                ("nation", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=10)),
                ("age", models.CharField(max_length=10)),
                ("league", models.CharField(max_length=50)),
                ("club", models.CharField(max_length=50)),
                ("club_id", models.IntegerField()),
                ("matches_played_league", models.IntegerField()),
                ("matches_played_competition", models.IntegerField()),
                ("starts_league", models.IntegerField()),
                ("start_competition", models.IntegerField()),
                ("minutes_league", models.IntegerField()),
                ("minutes_competition", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
